import type { Metadata } from "next";
import Providers from "@/Provider/Providers";
import "./globals.css"; // 전역 스타일 import
import { nanumGothic } from "@/app/utils/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ margin: 0, padding: 0 }}>
      <head></head>
      <body className={nanumGothic.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
